trigger:
  - develop

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: common
      type: git
      ref: main
      name: lowcode-test
stages:
  - stage: build
    jobs:
      - job: docker
        pool:
          vmImage: ubuntu-latest
        steps:
          - publish: $(System.DefaultWorkingDirectory)/develop.yaml
            artifact: DeployDevelop
          - task: Docker@2
            inputs:
              containerRegistry: 'acr'
              repository: 'iot/alfred'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: $(Build.BuildNumber)
  - stage: deploy
    jobs:
      - deployment: kubernetes
        environment: 'development'
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: DeployDevelop
                - script: sed -i "s/qixindev.azurecr.io\/iot\/alfred:[a-zA-Z]*[_]*[a-zA-Z]*-[0-9]*[.][0-9]*/qixindev.azurecr.io\/iot\/alfred:$(Build.BuildNumber)/g" $(Pipeline.Workspace)/DeployDevelop/develop.yaml
                - task: Kubernetes@1
                  inputs:
                    connectionType: 'Kubernetes Service Connection'
                    kubernetesServiceEndpoint: 'aks-dev'
                    namespace: 'default'
                    command: 'apply'
                    arguments: '-f $(Pipeline.Workspace)/DeployDevelop/develop.yaml'
                    secretType: 'dockerRegistry'
                    containerRegistryType: 'Azure Container Registry'
  - stage: test
    jobs:
      - job: ApiTest
        continueOnError: false
        steps:
          - checkout: common
          - script: pip install -r requirements.txt
            displayName: InstallPython
          - script: python3 test_alfred.py
            displayName: TestAlfred
