system:
  env: develop
  port: 8080
  db-type: "pgsql"
  use-redis: true
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
  mode: dev
  oss-type: "aliyun-oss"
  host: ""

zap:
  level: "debug"
  format: "console"
  prefix: "[Qixin/Platform]"
  director: "data/log"
  show-line: true
  encode-level: "CapitalColorLevelEncoder"
  stacktrace-key: "stacktrace"
  log-in-console: true
  max-age: 72

tencent-cos:
  bucket:
  region:
  secret-id:
  secret-key:
  base-url:
  path-prefix:

aliyun-oss:
  endpoint: ""
  access-key-id: ""
  access-key-secret: ""
  bucket-name: ""
  bucket-url: ""
  base-path: ""

azure-blob:
  account-name:
  account-key:
  container: "iothotcold"

rabbit-mq:
  amqp: "amqp://rabbitmq:rabbitmq@rabbitmq:5672/"

pgsql:
  host: "postgres"
  port: "5432"
  config: ""
  db-name: "iot"
  username: "qixin"
  password: "qixin"
  max-idle-conns: 10
  max-open-conns: 1000
  log-mode: "info"
  log-zap: false
