system:
  env: develop
  port: 8080
  db-type: "pgsql"
  use-redis: true
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
  mode: dev
  oss-type: "aliyun-oss"
  host: "159.27.188.207"

zap:
  level: "debug"
  format: "console"
  prefix: "[Qixin/Platform]"
  director: "data/log"
  show-line: true
  encode-level: "CapitalColorLevelEncoder"
  stacktrace-key: "stacktrace"
  log-in-console: true
  max-age: 72

tencent-cos:
  bucket:
  region:
  secret-id:
  secret-key:
  base-url:
  path-prefix:

aliyun-oss:
  endpoint: "oss-cn-shenzhen.aliyuncs.com"
  access-key-id: "LTAI5tSai5KqkwSbmWgJ3JR2"
  access-key-secret: "PxdgHsONHVreCxz6aEUdGlmuUH7Go9"
  bucket-name: "iothotcold"
  bucket-url: "iot-hotcold.oss-cn-shenzhen.aliyuncs.com"
  base-path: "hotcold/"

azure-blob:
  account-name:
  account-key:
  container: "iothotcold"

rabbit-mq:
  amqp: "amqp://default_user_HZRmWEqPB_e9fTybSWz:RyamqGvqv7yhkfsJykmh5O8Nb0rm-JKa@127.0.0.1:5672/"

pgsql:
  host: "dev.postgres.database.chinacloudapi.cn"
  port: "5432"
  config: ""
  db-name: "iot"
  username: "qixin"
  password: "Qx20190822"
  max-idle-conns: 10
  max-open-conns: 1000
  log-mode: "info"
  log-zap: false
