apiVersion: v1
kind: Service
metadata:
  labels:
    app: accounts
  name: accounts
spec:
  ports:
    - port: 80
  selector:
    app: accounts
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - env:
            - name: CONFIG_PATH
              value: "config.dev.yaml"
            - name: DEPLOY_TYPE
              value: "k8s"
            - name: SERVICE_CONFIG_MAP
              value: "service-config"
            - name: NANE_SPACE
              value: "default"
            - name: RELEASE_TYPE
              value: "first"
          image: qixindev.azurecr.io/iot/accounts:develop-20230321.1
          name: accounts
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /root/.kube
              name: kubeconfig
            - mountPath: /app/data/
              name: backenddata
            - name: timezone
              mountPath: /etc/localtime
              subPath: Shanghai
          resources:
            limits:
              cpu: "64m"
              memory: 512Mi
            requests:
              cpu: 6m
              memory: 8Mi
      imagePullSecrets:
        - name: acrcred
      volumes:
        - name: kubeconfig
          configMap:
            name: kubeconfig
            items:
              - key: config
                path: config
        - name: backenddata
          hostPath:
            path: /etc/data/accounts/
        - name: timezone
          configMap:
            name: timezone