version: '3'

services:
  alfred:
    build: .
    container_name: alfred
    ports:
      - "80:80"
    environment:
      - CONFIG_PATH=config.dev.yaml
      - DEPLOY_TYPE=local
    volumes:
      - /etc/localtime:/etc/localtime
      - ./config.dev.yaml:/app/config.dev.yaml
    networks:
      - qixin
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=qixin
      - POSTGRES_PASSWORD=Qx20190822
      - POSTGRES_DB=accounts
    networks:
      - qixin

networks:
  qixin:
    driver: bridge
