version: '3'

services:
  accounts:
    build: .
    container_name: accounts
    ports:
      - "80:80"
    networks:
      - qixin
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=qixin
      - POSTGRES_PASSWORD=Qx20190822
      - POSTGRES_DB=accounts
    networks:
      - qixin

networks:
  qixin:
    driver: bridge
